version: "3.8"

services:
    lab:
        build: ./Vuln_Lab_4
        container_name: ctf_lab_4
        ports:
            - 4444:80
        restart: always
        volumes:
            - ./Vuln_Lab_4/Source:/var/www/html                               
        links:
            - "db"

    db:
        build: ./db
        restart: always
        container_name: db4
        expose:
            - 3306
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_USER=user
            - MYSQL_PASSWORD=pass
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
